imports:
    - { resource: "@SyliusProductBundlePlugin/config/resources/*.yaml" }
    - { resource: "@SyliusProductBundlePlugin/config/services.xml" }
    - { resource: "@SyliusProductBundlePlugin/config/twig_hooks/**/*.yaml" }

framework:
    messenger:
        buses:
            sylius_product_bundle.command_bus: ~
