sylius_resource:
    resources:
        sylius_product_bundle.product_bundle:
            driver: doctrine/orm
            classes:
                model: Sylius\ProductBundlePlugin\Entity\ProductBundle
                interface: Sylius\ProductBundlePlugin\Entity\ProductBundleInterface
                form: Sylius\ProductBundlePlugin\Form\Type\ProductBundleType
